var FOUR_CC = {
   "subtitles": 
    {
        "spu ":"DVD Subtitles",
        "spub":"DVD Subtitles",
        "dvbs":"DVB Subtitles",
        "subt":"Text subtitles with various tags",
        "XSUB":"DivX XSUB subtitles",
        "xsub":"DivX XSUB subtitles",
        "DXSB":"DivX XSUB subtitles",
        "ssa ":"SubStation Alpha subtitles",
        "TEXT":"Plain text subtitles",
        "telx":"Teletext",
        "kate":"Kate subtitles",
        "cmml":"CMML annotations/metadata",
        "t140":"ITU T.140 subtitles",
        "usf ":"USF subtitles",
        "ogt ":"OGT subtitles",
        "cvd ":"CVD subtitles",
        "bdpg":"BD subtitles"
   
    },
    "video": 
    {
        "mpgv":"MPEG-1/2 Video",
        "mp1v":"MPEG-1/2 Video",
        "mpeg":"MPEG-1/2 Video",
        "mpg1":"MPEG-1/2 Video",
        "mp2v":"MPEG-1/2 Video",
        "MPEG":"MPEG-1/2 Video",
        "mpg2":"MPEG-1/2 Video",
        "MPG2":"MPEG-1/2 Video",
        "PIM1":"Pinnacle DC1000 (MPEG-1 Video)",
        "hdv1":"HDV 720p30 (MPEG-2 Video)",
        "hdv2":"Sony HDV (MPEG-2 Video)",
        "hdv3":"FCP HDV (MPEG-2 Video)",
        "hdv5":"HDV 720p25 (MPEG-2 Video)",
        "hdv6":"HDV 1080p24 (MPEG-2 Video)",
        "hdv7":"HDV 1080p25 (MPEG-2 Video)",
        "hdv8":"HDV 1080p30 (MPEG-2 Video)",
        "mx5n":"MPEG2 IMX NTSC 525/60 50mb/s (FCP)",
        "mx5p":"MPEG2 IMX PAL 625/60 50mb/s (FCP)",
        "mx4n":"MPEG2 IMX NTSC 525/60 40mb/s (FCP)",
        "mx4p":"MPEG2 IMX PAL 625/50 40mb/s (FCP)",
        "mx3n":"MPEG2 IMX NTSC 525/60 30mb/s (FCP)",
        "mx3p":"MPEG2 IMX NTSC 625/50 30mb/s (FCP)",
        "xdv1":"XDCAM HD",
        "xdv2":"XDCAM HD 1080i60 35mb/s",
        "xdv3":"XDCAM HD 1080i50 35mb/s",
        "xdv4":"XDCAM HD",
        "xdv5":"XDCAM HD",
        "xdv6":"XDCAM HD 1080p24 35mb/s",
        "xdv7":"XDCAM HD 1080p25 35mb/s",
        "xdv8":"XDCAM HD 1080p30 35mb/s",
        "xdv9":"XDCAM HD",
        "xdva":"XDCAM",
        "xdvb":"XDCAM",
        "xdvc":"XDCAM",
        "xdvd":"XDCAM",
        "xdve":"XDCAM",
        "xdvf":"XDCAM",
        "xd5a":"XDCAM",
        "xd5b":"XDCAM",
        "xd5c":"XDCAM",
        "xd5d":"XDCAM",
        "xd5e":"XDCAM",
        "xd5f":"XDCAM",
        "xd59":"XDCAM",
        "AVmp":"AVID IMX PAL",
        "MMES":"Matrox MPEG-2",
        "mmes":"Matrox MPEG-2",
        "PIM2":"Pinnacle MPEG-2",
        "LMP2":"Lead MPEG-2",
        "VCR2":"ATI VCR-2",
        "mp4v":"MPEG-4 Video",
        "DIVX":"MPEG-4 Video",
        "divx":"MPEG-4 Video",
        "MP4S":"MPEG-4 Video",
        "mp4s":"MPEG-4 Video",
        "M4S2":"MPEG-4 Video",
        "m4s2":"MPEG-4 Video",
        "MP4V":"MPEG-4 Video",
        "\\x04\\x00\\x00\\x00":"MPEG-4 Video",
        "m4cc":"MPEG-4 Video",
        "M4CC":"MPEG-4 Video",
        "FMP4":"MPEG-4 Video",
        "fmp4":"MPEG-4 Video",
        "DCOD":"MPEG-4 Video",
        "MVXM":"MPEG-4 Video",
        "PM4V":"MPEG-4 Video",
        "M4T3":"MPEG-4 Video",
        "GEOX":"MPEG-4 Video",
        "GEOV":"MPEG-4 Video",
        "DMK2":"MPEG-4 Video",
        "WV1F":"MPEG-4 Video",
        "DIGI":"MPEG-4 Video",
        "INMC":"MPEG-4 Video",
        "SN40":"MPEG-4 Video",
        "EPHV":"MPEG-4 Video",
        "xvid":"Xvid MPEG-4 Video",
        "XVID":"Xvid MPEG-4 Video",
        "XviD":"Xvid MPEG-4 Video",
        "XVIX":"Xvid MPEG-4 Video",
        "xvix":"Xvid MPEG-4 Video",
        "DX50":"DivX MPEG-4 Video",
        "dx50":"DivX MPEG-4 Video",
        "BLZ0":"Blizzard MPEG-4 Video",
        "DXGM":"Electronic Arts Game MPEG-4 Video",
        "3IV2":"3ivx MPEG-4 Video",
        "3iv2":"3ivx MPEG-4 Video",
        "UMP4":"UB MPEG-4 Video",
        "SEDG":"Samsung MPEG-4 Video",
        "RMP4":"REALmagic MPEG-4 Video",
        "HDX4":"Jomigo HDX4 (MPEG-4 Video)",
        "hdx4":"Jomigo HDX4 (MPEG-4 Video)",
        "SMP4":"Samsung SMP4 (MPEG-4 Video)",
        "smp4":"Samsung SMP4 (MPEG-4 Video)",
        "fvfw":"FFmpeg MPEG-4",
        "FVFW":"FFmpeg MPEG-4",
        "FFDS":"FFDShow MPEG-4",
        "VIDM":"vidm 4.01 codec",
        "3IV1":"3ivx delta 3.5 MPEG-4 Video",
        "3iv1":"3ivx delta 3.5 MPEG-4 Video",
        "DIV1":"MS MPEG-4 Video v1",
        "div1":"MS MPEG-4 Video v1",
        "MPG4":"MS MPEG-4 Video v1",
        "mpg4":"MS MPEG-4 Video v1",
        "mp41":"MS MPEG-4 Video v1",
        "DIV2":"MS MPEG-4 Video v2",
        "div2":"MS MPEG-4 Video v2",
        "MP42":"MS MPEG-4 Video v2",
        "mp42":"MS MPEG-4 Video v2",
        "DIV3":"MS MPEG-4 Video v3",
        "MPG3":"MS MPEG-4 Video v3",
        "mpg3":"MS MPEG-4 Video v3",
        "div3":"MS MPEG-4 Video v3",
        "MP43":"MS MPEG-4 Video v3",
        "mp43":"MS MPEG-4 Video v3",
        "DIV4":"MS MPEG-4 Video v3",
        "div4":"MS MPEG-4 Video v3",
        "DIV5":"MS MPEG-4 Video v3",
        "div5":"MS MPEG-4 Video v3",
        "DIV6":"MS MPEG-4 Video v3",
        "div6":"MS MPEG-4 Video v3",
        "divf":"DivX 4.12",
        "DIVF":"DivX 4.12",
        "COL1":"MS MPEG-4 Video v3",
        "col1":"MS MPEG-4 Video v3",
        "COL0":"MS MPEG-4 Video v3",
        "col0":"MS MPEG-4 Video v3",
        "AP41":"MS MPEG-4 Video v3",
        "3IVD":"MS MPEG-4 Video v3",
        "3ivd":"MS MPEG-4 Video v3",
        "3VID":"MS MPEG-4 Video v3",
        "3vid":"MS MPEG-4 Video v3",
        "DVX3":"MS MPEG-4 Video v3",
        "SVQ1":"SVQ-1 (Sorenson Video v1)",
        "svq1":"SVQ-1 (Sorenson Video v1)",
        "svqi":"SVQ-1 (Sorenson Video v1)",
        "SVQ3":"SVQ-3 (Sorenson Video v3)",
        "H264":"H264 - MPEG-4 AVC (part 10)",
        "h264":"H264 - MPEG-4 AVC (part 10)",
        "x264":"H264 - MPEG-4 AVC (part 10)",
        "X264":"H264 - MPEG-4 AVC (part 10)",
        "avc1":"H264 - MPEG-4 AVC (part 10)",
        "AVC1":"H264 - MPEG-4 AVC (part 10)",
        "VSSH":"Vanguard VSS H264",
        "VSSW":"Vanguard VSS H264",
        "vssh":"Vanguard VSS H264",
        "DAVC":"Dicas MPEGable H.264/MPEG-4 AVC",
        "davc":"Dicas MPEGable H.264/MPEG-4 AVC",
        "H263":"H263",
        "h263":"H263",
        "VX1K":"H263",
        "s263":"H263",
        "S263":"H263",
        "U263":"H263",
        "u263":"H263",
        "D263":"DEC H263",
        "L263":"LEAD H263",
        "M263":"Microsoft H263",
        "X263":"Xirlink H263",
        "ZyGo":"ITU H263+",
        "I263":"I263.I",
        "i263":"I263.I",
        "ILVR":"ITU H263+",
        "viv1":"H263+",
        "vivO":"H263+",
        "viv2":"H263+",
        "U263":"UB H263+",
        "FLV1":"Flash Video",
        "flv ":"Flash Video",
        "H261":"H.261",
        "h261":"H.261",
        "FLIC":"Flic Video",
        "MJPG":"Motion JPEG Video",
        "mjpg":"Motion JPEG Video",
        "mjpa":"Motion JPEG Video",
        "jpeg":"Motion JPEG Video",
        "JPEG":"Motion JPEG Video",
        "JFIF":"Motion JPEG Video",
        "JPGL":"Motion JPEG Video",
        "AVDJ":"Motion JPEG Video",
        "MMJP":"Motion JPEG Video",
        "QIVG":"Motion JPEG Video",
        "AVRn":"Avid Motion JPEG",
        "AVDJ":"Avid Motion JPEG",
        "ADJV":"Avid Motion JPEG",
        "dmb1":"Motion JPEG OpenDML Video",
        "ijpg":"Intergraph JPEG Video",
        "IJPG":"Intergraph JPEG Video",
        "ACDV":"ACD Systems Digital",
        "SLMJ":"SL M-JPEG",
        "mjpb":"Motion JPEG B Video",
        "LJPG":"Lead Motion JPEG Video",
        "SP5X":"Sunplus Motion JPEG Video",
        "SP53":"Sunplus Motion JPEG Video",
        "SP54":"Sunplus Motion JPEG Video",
        "SP55":"Sunplus Motion JPEG Video",
        "SP56":"Sunplus Motion JPEG Video",
        "SP57":"Sunplus Motion JPEG Video",
        "SP58":"Sunplus Motion JPEG Video",
        "dv  ":"DV Video",
        "dvsl":"DV Video",
        "DVSD":"DV Video",
        "dvsd":"DV Video",
        "DVCS":"DV Video",
        "dvcs":"DV Video",
        "dvhd":"DV Video",
        "dvhp":"DV Video",
        "dvhq":"DV Video",
        "dvh3":"DV Video",
        "dvh5":"DV Video",
        "dvh6":"DV Video",
        "dv1n":"DV Video",
        "dv1p":"DV Video",
        "dvc ":"DV Video",
        "dv25":"DV Video",
        "dvh1":"DV Video",
        "dvs1":"DV Video",
        "dvcp":"DV Video PAL",
        "dvp ":"DV Video Pro",
        "dvpp":"DV Video Pro PAL",
        "dv50":"DV Video C Pro 50",
        "dv5p":"DV Video C Pro 50 PAL",
        "dv5n":"DV Video C Pro 50 NTSC",
        "AVdv":"AVID DV",
        "AVd1":"AVID DV",
        "CDVC":"Canopus DV Video",
        "cdvc":"Canopus DV Video",
        "CDVH":"Canopus DV Video",
        "cdvh":"Canopus DV Video",
        "WMV1":"Windows Media Video 7",
        "wmv1":"Windows Media Video 7",
        "WMV2":"Windows Media Video 8",
        "wmv2":"Windows Media Video 8",
        "WMV3":"Windows Media Video 9",
        "wmv3":"Windows Media Video 9",
        "WMVA":"Windows Media Video Advanced Profile",
        "wmva":"Windows Media Video Advanced Profile",
        "WVP2":"Windows Media Video Advanced Profile",
        "wvp2":"Windows Media Video Advanced Profile",
        "WVC1":"Windows Media Video VC1",
        "wvc1":"Windows Media Video VC1",
        "vc-1":"Windows Media Video VC1",
        "VC-1":"Windows Media Video VC1",
        "MSVC":"Microsoft Video 1",
        "msvc":"Microsoft Video 1",
        "CRAM":"Microsoft Video 1",
        "cram":"Microsoft Video 1",
        "WHAM":"Microsoft Video 1",
        "wham":"Microsoft Video 1",
        "mrle":"Microsoft RLE Video",
        "WRLE":"Microsoft RLE Video",
        "\\x01\\x00\\x00\\x00":"Microsoft RLE Video",
        "\\x02\\x00\\x00\\x00":"Microsoft RLE Video",
        "IV31":"Indeo Video v3",
        "iv31":"Indeo Video v3",
        "IV32":"Indeo Video v3",
        "iv32":"Indeo Video v3",
        "HFYU":"Huff YUV Video",
        "FFVH":"Huff YUV Video",
        "VP3 ":"On2's VP3 Video",
        "VP30":"On2's VP3 Video",
        "vp30":"On2's VP3 Video",
        "VP31":"On2's VP3 Video",
        "vp31":"On2's VP3 Video",
        "VP5 ":"On2's VP5 Video",
        "VP50":"On2's VP5 Video",
        "VP62":"On2's VP6.2 Video",
        "vp62":"On2's VP6.2 Video",
        "VP60":"On2's VP6.0 Video",
        "VP61":"On2's VP6.1 Video",
        "VP6F":"On2's VP6.2 Video (Flash)",
        "FLV4":"On2's VP6.2 Video (Flash)",
        "VP6A":"On2's VP6 A Video",
        "VP80":"Google/On2's VP8 Video",
        "theo":"Xiph.org's Theora Video",
        "Thra":"Xiph.org's Theora Video",
        "tark":"Xiph.org's Tarkin Video",
        "ASV1":"Asus V1 Video",
        "ASV2":"Asus V2 Video",
        "FFV1":"FFMpeg Video 1",
        "VCR1":"ATI VCR1 Video",
        "CLJR":"Creative Logic AccuPak",
        "RV10":"Real Video 1.0",
        "rv10":"Real Video 1.0",
        "RV13":"Real Video 1.3",
        "rv13":"Real Video 1.3",
        "RV20":"Real Video 2.0",
        "rv20":"Real Video 2.0",
        "RV30":"Real Video 3.0",
        "rv30":"Real Video 3.0",
        "RV40":"Real Video 4.0",
        "rv40":"Real Video 4.0",
        "rpza":"Apple Video",
        "azpr":"Apple Video",
        "RPZA":"Apple Video",
        "AZPR":"Apple Video",
        "smc ":"Apple graphics",
        "CVID":"Cinepak Video",
        "cvid":"Cinepak Video",
        "TSCC":"TechSmith Camtasia Screen Capture",
        "tscc":"TechSmith Camtasia Screen Capture",
        "CSCD":"CamStudio Screen Codec",
        "cscd":"CamStudio Screen Codec",
        "ZMBV":"DosBox Capture Codec",
        "VMnc":"VMware Video",
        "FPS1":"FRAPS: Realtime Video Capture",
        "fps1":"FRAPS: Realtime Video Capture",
        "DUCK":"Duck TrueMotion v1 Video",
        "PVEZ":"Duck TrueMotion v1 Video",
        "TM20":"Duck TrueMotion v2.0 Video",
        "SNOW":"FFMpeg SNOW wavelet Video",
        "snow":"FFMpeg SNOW wavelet Video",
        "rle ":"Apple QuickTime RLE Video",
        "qdrw":"Apple QuickDraw Video",
        "QPEG":"QPEG Video",
        "Q1.0":"QPEG Video",
        "Q1.1":"QPEG Video",
        "ULTI":"IBM Ultimotion Video",
        "VIXL":"Miro/Pinnacle VideoXL Video",
        "XIXL":"Miro/Pinnacle VideoXL Video",
        "PIXL":"Pinnacle VideoXL Video",
        "LOCO":"LOCO Video",
        "WNV1":"Winnov WNV1 Video",
        "AASC":"Autodesc RLE Video",
        "IV20":"Indeo Video v2",
        "RT21":"Indeo Video v2",
        "FSV1":"Flash Screen Video",
        "KMVC":"Karl Morton's Video Codec (Worms)",
        "RJPG":"Nuppel Video",
        "NUV1":"Nuppel Video",
        "SMK2":"Smacker Video",
        "SMK4":"Smacker Video",
        "CAVS":"Chinese AVS",
        "AVs2":"Chinese AVS",
        "avs2":"Chinese AVS",
        "AVdn":"DNxHD",
        "AVdh":"DNxHR",
        "8BPS":"8BPS",
        "ML2O":"Mimic",
        "CDG ":"CD-G Video",
        "FRWU":"Forward Uncompressed",
        "IV50":"Indeo Video v5",
        "iv50":"Indeo Video v5",
        "YV12":"Planar 4:2:0 YVU",
        "yv12":"Planar 4:2:0 YVU",
        "YVU9":"Planar 4:1:0 YVU",
        "I410":"Planar 4:1:0 YUV",
        "I411":"Planar 4:1:1 YUV",
        "I420":"Planar 4:2:0 YUV",
        "IYUV":"Planar 4:2:0 YUV",
        "I422":"Planar 4:2:2 YUV",
        "I440":"Planar 4:4:0 YUV",
        "I444":"Planar 4:4:4 YUV",
        "J420":"Planar 4:2:0 YUV full scale",
        "J422":"Planar 4:2:2 YUV full scale",
        "J440":"Planar 4:4:0 YUV full scale",
        "J444":"Planar 4:4:4 YUV full scale",
        "YUVP":"Palettized YUV with palette element Y:U:V:A",
        "YUVA":"Planar YUV 4:4:4 Y:U:V:A",
        "RGBP":"Palettized RGB with palette element R:G:B",
        "RGB2":"8 bits RGB",
        "RV15":"15 bits RGB",
        "RV16":"16 bits RGB",
        "RV24":"24 bits RGB",
        "RV32":"32 bits RGB",
        "RGBA":"32 bits RGBA",
        "GREY":"8 bits greyscale",
        "Y800":"8 bits greyscale",
        "Y8  ":"8 bits greyscale",
        "UYVY":"Packed YUV 4:2:2, U:Y:V:Y",
        "UYNV":"Packed YUV 4:2:2, U:Y:V:Y",
        "UYNY":"Packed YUV 4:2:2, U:Y:V:Y",
        "Y422":"Packed YUV 4:2:2, U:Y:V:Y",
        "HDYC":"Packed YUV 4:2:2, U:Y:V:Y",
        "AVUI":"Packed YUV 4:2:2, U:Y:V:Y",
        "uyv1":"Packed YUV 4:2:2, U:Y:V:Y",
        "2vuy":"Packed YUV 4:2:2, U:Y:V:Y",
        "2Vuy":"Packed YUV 4:2:2, U:Y:V:Y",
        "2Vu1":"Packed YUV 4:2:2, U:Y:V:Y",
        "VYUY":"Packed YUV 4:2:2, V:Y:U:Y",
        "YUY2":"Packed YUV 4:2:2, Y:U:Y:V",
        "YUYV":"Packed YUV 4:2:2, Y:U:Y:V",
        "YUNV":"Packed YUV 4:2:2, Y:U:Y:V",
        "V422":"Packed YUV 4:2:2, Y:U:Y:V",
        "YVYU":"Packed YUV 4:2:2, Y:V:Y:U",
        "Y211":"Packed YUV 2:1:1, Y:U:Y:V ",
        "cyuv":"Creative Packed YUV 4:2:2, U:Y:V:Y, reverted",
        "CYUV":"Creative Packed YUV 4:2:2, U:Y:V:Y, reverted",
        "v210":"10-bit 4:2:2 Component YCbCr",
        "NV12":"Planar  Y, Packet UV (420)",
        "imve":"Interplay MVE Video",
        "INPV":"Interplay MVE Video",
        "IDCI":"Id Quake II CIN Video",
        "4XMV":"4X Technologies Video",
        "4xmv":"4X Technologies Video",
        "RoQv":"Id RoQ Video",
        "MDEC":"PSX MDEC Video",
        "VMDV":"Sierra VMD Video",
        "vmdv":"Sierra VMD Video",
        "drac":"Dirac",
        "png ":"PNG Image",
        "ppm ":"PPM Image",
        "pgm ":"PGM Image",
        "pgmy":"PGM YUV Image",
        "pam ":"PAM Image",
        "MJLS":"Lossless JPEG",
        "jpeg":"JPEG",
        "JPEG":"JPEG",
        "bmp ":"BMP Image",
        "tiff":"TIFF Image",
        "gif ":"GIF Image",
        "tga ":"Truevision Targa Image",
        "mtga":"Truevision Targa Image",
        "MTGA":"Truevision Targa Image",
        "sgi ":"SGI Image",
        "pnm ":"Portable Anymap Image",
        "pcx ":"Personal Computer Exchange Image",
        "apch":"Apple ProRes 422 High Quality BE",
        "hcpa":"Apple ProRes 422 High Quality LE",
        "apcn":"Apple ProRes 422 Standard Definition BE",
        "ncpa":"Apple ProRes 422 Standard Definition LE",
        "apcs":"Apple ProRes 422 LT BE",
        "scpa":"Apple ProRes 422 LT LE",
        "apco":"Apple ProRes 422 Proxy BE",
        "ocpa":"Apple ProRes 422 Proxy LE",
        "ap4h":"Apple ProRes 444 BE",
        "h4pa":"Apple ProRes 444 LE",
        "pxlt":"Apple Pixlet",
        "CFHD":"Cineform"
    },
    "audio": 
    {
        "WMA1":"Windows Media Audio 1",
        "wma1":"Windows Media Audio 1",
        "WMA2":"Windows Media Audio 2",
        "wma2":"Windows Media Audio 2",
        "wma ":"Windows Media Audio 2",
        "WMAP":"Windows Media Audio Professional",
        "wmap":"Windows Media Audio Professional",
        "WMAL":"Windows Media Audio Lossless",
        "wmal":"Windows Media Audio Lossless",
        "WMAS":"Windows Media Audio Voice (Speech)",
        "wmas":"Windows Media Audio Voice (Speech)",
        "dvau":"DV Audio",
        "vdva":"DV Audio",
        "dvca":"DV Audio",
        "RADV":"DV Audio",
        "MAC3":"MACE-3 Audio",
        "MAC6":"MACE-6 Audio",
        "MPC ":"MUSEPACK7 Audio",
        "MPCK":"MUSEPACK8 Audio",
        "MPC8":"MUSEPACK8 Audio",
        "14_4":"RealAudio 1.0",
        "lpcJ":"RealAudio 1.0",
        "28_8":"RealAudio 2.0",
        "sipr":"RealAudio Sipr",
        "mpga":"MPEG Audio layer 1/2/3",
        "mp3 ":"MPEG Audio layer 1/2/3",
        ".mp3":"MPEG Audio layer 1/2/3",
        "MP3 ":"MPEG Audio layer 1/2/3",
        "LAME":"MPEG Audio layer 1/2/3",
        "ms\\x00\\x50":"MPEG Audio layer 1/2/3",
        "ms\\x00\\x55":"MPEG Audio layer 1/2/3",
        "a52 ":"A52 Audio (aka AC3)",
        "a52b":"A52 Audio (aka AC3)",
        "ac-3":"A52 Audio (aka AC3)",
        "ms\\x20\\x00":"A52 Audio (aka AC3)",
        "eac3":"A/52 B Audio (aka E-AC3)",
        "dts ":"DTS Audio",
        "dtsb":"DTS Audio",
        "ms\\x20\\x01":"DTS Audio",
        "mp4a":"MPEG AAC Audio",
        "aac ":"MPEG AAC Audio",
        "als ":"MPEG-4 Audio Lossless (ALS)",
        "4xma":"4X Technologies Audio",
        "ADEA":"EA ADPCM Audio",
        "idpc":"Interplay DPCM Audio",
        "RoQa":"Id RoQ DPCM Audio",
        "DCIA":"Delphine CIN Audio",
        "xa  ":"PSX XA ADPCM Audio",
        "adx ":"ADX ADPCM Audio",
        "AIWS":"Westwood IMA ADPCM audio",
        "ms\\x00\\x02":"MS ADPCM audio",
        "vmda":"Sierra VMD Audio",
        "g726":"G.726 ADPCM Audio",
        "SWFa":"Flash ADPCM Audio",
        "ms\\x00\\x11":"IMA WAV ADPCM Audio",
        "imav":"IMA AMV ADPCM Audio",
        "samr":"AMR narrow band",
        "sawb":"AMR wide band",
        "flac":"FLAC (Free Lossless Audio Codec)",
        "alac":"Apple Lossless Audio Codec",
        "QDM2":"QDM2 Audio",
        "cook":"Cook Audio",
        "TTA1":"The Lossless True Audio",
        "shn ":"Shorten Lossless Audio",
        "shrn":"Shorten Lossless Audio",
        "WVPK":"WavPack",
        "wvpk":"WavPack",
        "gsm ":"GSM Audio",
        "agsm":"Microsoft GSM Audio",
        "atr1":"atrac 1",
        "atrc":"atrac 3",
        "\\x70\\x02\\x00\\x00":"atrac 3",
        "SONC":"Sonic",
        "\\x01\\x04\\x00\\x00":"IMC",
        "\\x22\\x00\\x00\\x00":"TrueSpeech",
        "NELL":"NellyMoser ASAO",
        "APE ":"Monkey's Audio",
        "mlp ":"MLP/TrueHD Audio",
        "trhd":"TrueHD Audio",
        "Qclp":"QCELP Audio",
        "spx ":"Speex Audio",
        "spxr":"Speex Audio",
        "vorb":"Vorbis Audio",
        "302m":"302M Audio",
        "lpcm":"DVD LPCM Audio",
        "apcm":"DVD-Audio LPCM Audio",
        "bpcm":"BD LPCM Audio",
        "sdds":"SDDS Audio",
        "sddb":"SDDS Audio",
        "MIDI":"MIDI Audio",
        "s8  ":"PCM S8",
        "u8  ":"PCM U8",
        "s16l":"PCM S16 LE",
        "s16b":"PCM S16 BE",
        "twos":"PCM 16 LE",
        "sowt":"PCM 16 BE",
        "u16l":"PCM U16 LE",
        "u16b":"PCM U16 BE",
        "s24l":"PCM S24 LE",
        "42ni":"PCM S24 LE",
        "s24b":"PCM S24 BE",
        "in24":"PCM S24 BE",
        "u24l":"PCM U24 LE",
        "u24b":"PCM U24 BE",
        "s32l":"PCM S32 LE",
        "23ni":"PCM S32 LE",
        "s32b":"PCM S32 BE",
        "in32":"PCM S32 BE",
        "u32l":"PCM U32 LE",
        "u32b":"PCM U32 BE",
        "alaw":"PCM ALAW",
        "mlaw":"PCM MU-LAW",
        "ulaw":"PCM MU-LAW",
        "daud":"PCM DAUD",
        "fi32":"32 bits fixed float",
        "f32l":"32 bits float LE",
        "fl32":"32 bits float LE",
        "f32b":"32 bits float BE",
        "f64l":"64 bits float LE",
        "f64b":"64 bits float BE",
        "TWIN":"TwinVQ"
    }
}

function FourCC(){
    this.FOUR_CC = FOUR_CC;
}

FourCC.prototype.find_fourcc = function(fourcc){
    return FOUR_CC['subtitles'][fourcc]
        ||FOUR_CC['video'][fourcc]
        ||FOUR_CC['audio'][fourcc];
}
